---
- name: Checking chrony
  ansible.builtin.yum:
    name: chrony
    update_cache: true

# TODO : Faire du déclaratif
- name: Set timezone
  command: timedatectl set-timezone Europe/Paris

- name: Configure chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'

- name: Starting chronyd service
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: true
