---
- name: Configure yum repo
  ansible.builtin.yum_repository:
    name: '{{ common_yum_repo_name }}'
    description: default yum repo
    baseurl: '{{ common_yum_repo_url }}'
    gpgcheck: false
    enabled: true
    state: present

- name: Install minimal packages
  ansible.builtin.yum:
    name:
      - nfs-utils
      - cifs-utils
    state: present
    update_cache: true

- name: Installation dev packages
  ansible.builtin.yum:
    name:
      - vim
      - tree
      - bind-utils
      - traceroute
      - NetworkManager
      - telnet
      - net-tools
    state: present
    update_cache: true

- name: Remove repository (and clean up left-over metadata)
  ansible.builtin.yum_repository:
    name: '{{ common_yum_repo_name }}'
    state: absent
  notify: yum-clean-metadata
