---
- name: Configure yum repo
  ansible.builtin.yum_repository:
    name: '{{ apache_yum_repo_name }}'
    description: default yum repo
    baseurl: '{{ apache_yum_repo_url }}'
    gpgcheck: false
    enabled: true
    state: present

- name: Install minimal packages
  ansible.builtin.yum:
    name:
      - httpd
    state: present
    update_cache: true

- name: Remove repository (and clean up left-over metadata)
  ansible.builtin.yum_repository:
    name: '{{ apache_yum_repo_name }}'
    state: absent
  notify: yum-clean-metadata
