---
- name: Ping
  hosts: all
  tasks:
    - name: pingpong
      ansible.builtin.ping:

    # - name: wildfly
    #   ansible.builtin.yum:
    #     name:
    #       - java-11-openjdk-devel
    #     state: present
    - name: fire
      ansible.builtin.service:
        name: firewalld
        state: stopped
