# -*- mode: ruby -*-
# vi: set ft=ruby :

base_box = "almalinux/8"
vm_memory = 512
vm_cpus = 1

Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
        master.vm.box = base_box
        master.vm.hostname = "master"
        master.vm.network "private_network", ip: "192.168.56.100"
        master.vm.synced_folder '.', '/home/vagrant/src/', mount_options: ["dmode=700", "fmode=600", "uid=1000", "gid=1000"]
        master.vm.provider "virtualbox" do |vb|
            vb.memory = vm_memory
            vb.cpus = vm_cpus
            master.vm.provision "shell", path: "./script/install-ansible.sh"
            master.ssh.port = 2222
            master.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
        end
    end
    config.vm.define "slave" do |slave|
        slave.vm.box = base_box
        slave.vm.hostname = "slave"
        slave.vm.network "private_network", ip: "192.168.56.101"
        slave.vm.provider "virtualbox" do |vb|
            vb.memory = vm_memory
            vb.cpus = vm_cpus
            slave.vm.provision "shell", path: "./script/install-ansible-requirements.sh"
            slave.ssh.port = 2223
            slave.vm.network "forwarded_port", guest: 22, host: 2223, id: "ssh"
        end
    end
    config.vm.provision "shell", path: "./script/default-config.sh"
end
